### ISSUE TITLE
Docs: Update wallet integration docs

### ISSUE THREAD

**Issue by jrwbabylonlab** [babylonlabs-io/bbn-wallet-connect#7]
Once babylonlabs-io/simple-staking#183 is done.
We should start updating all our wallet integration documentations. 
Please check documentations in all possible locations, including:
- https://github.com/babylonlabs-io/networks/blob/main/bbn-1/integration/wallet.md
- https://github.com/babylonlabs-io/simple-staking/blob/dev/docs/WalletIntegration.md
- https://docs.babylonlabs.io/docs/introduction/overview

**Comment by gbarkhatov** [comment]
I am closing this one to be a part of https://github.com/babylonlabs-io/bbn-wallet-connect/issues/16
