### ISSUE TITLE
Missing `getWalletProviderIcon` from the wallet interface

### ISSUE THREAD

**Issue by jrwbabylonlab** [babylonlabs-io/bbn-wallet-connect#8]
The `getWalletProviderIcon` is used here for the injectable wallet to show their icon. but it's not defined in our interface.
https://github.com/babylonlabs-io/simple-staking/blob/dev/src/app/components/Modals/ConnectModal.tsx#L52

**Comment by gbarkhatov** [comment]
Already there in our injectable interface
