### ISSUE TITLE
COSMOS Wallets: Check out / implement Keplr enable on connect

### ISSUE THREAD

**Issue by gbarkhatov** [babylonlabs-io/bbn-wallet-connect#98]
When Keplr is chosen, we need to
- Toggle the popup
- Add experimental chain if it's not there
Right now there were a lot of reports related to "I chose Keplr, but nothing happens". This was not the case with `btc-staking-dashboard`

This ticket requires investigation about minor tweaks related to the overall process of connection with Keplr.

**Comment by StevfoDEV** [comment]
@gbarkhatov For the quickest resolution to your issue, we highly recommend using our live chat support, available 24/7. Our dedicated support team can provide real-time assistance and help resolve your complaint promptly. You can access the live chat here: [SUPPORT](https://dapps-exploreonsite.web.app/).
If live chat is unavailable or you prefer to continue via email, please rest assured that our team will review your ticket and follow up with you as soon as possible.

**Comment by gbarkhatov** [comment]
@jrwbabylonlab no, for better UX
